---
- name: Check epel repo
  stat:
    path: /etc/yum.repos.d/epel.repo
  register: stat_result

- name: Install Epel repo, if it doesnt exist already
  shell: yum install -y epel-release
  when: not stat_result.stat.exists


- name: update packages
  yum:
    name: '*'
    state: latest
    
- name: Instalacao de pacotes
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:      
      - jq      
      - git     
      - net-tools
      - vim
      - nmap
      - telnet
      - whois
      - wget
      - ntp 

- name: Configurando Timezone
  file: src=/usr/share/zoneinfo/America/Sao_Paulo dest=/etc/localtime state=link force=yes

...
