---
- name: install ans start apache # nome para identificação do playbook
  hosts: webservers # aqui defino meus alvos neste caso o grupo webservers do hosts
  remote_user: vagrant # defino qual o usuario de acesso 
  become: yes # aqui defino que o user vai utilizar sudo su para tarefas do root 

  tasks: # indica o inicio das tasks
  - name: Install epel repo # nome para a tarefa 
    yum: name=epel-release state=present  # modulo + nome do pacote e state=present para instalar 

  - name: Install python bindigs for SELinux # nome para a tarefa 
    yum: name={{tem}} state:present # modulo + name = variavel (para gerar um loop) e o estado é instalar 
    with_items: # aqui chamo a variavel + os pacotes 
    - libselinux-python
    - libsemanage-python 
   
  - name: test to see if Selinux s running   # nome para a tarefa 
    command: getenforce # utilizo o modulo comando e passo o comando getenforce
    register: sestatus # aqui pego a saida do meu comando e adiciono a variavel "sestatus"
    changed_when: false

  - name: Install Apache 
    yum: name=httpd state=present 
    
  - name: Start Apache 
    service: name=httpd state=started enabled=yes

  

